# 编译打包、生成Docker镜像并推送到DockerHub上
name: manager-ui

# 触发条件
on: workflow_dispatch

# 全局环境变量
env:
  BRANCH: product
  MODULE:  manager-ui
  RUN_PORT: 8085
  DOCKERHUB_IMAGE: zhangqinghua/lilishop-manager-ui
# 步骤流程：
jobs:
  release:
    name: Build Project
    runs-on: ubuntu-latest
    outputs:
      download_url: ${{ steps.release_upload.outputs.browser_download_url }}
    steps:
      # 1. 拉取代码
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{env.BRANCH}}                            # 指定分支
      # 5. 登录DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: zhangqinghua
          password: 12345678go
      # 6. 构建Docker镜像并推送到DockerHub仓库
      - name: Build and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile
          tags: ${{env.DOCKERHUB_IMAGE}}:latest
          context: ./
          build-args: |
            MODULE=${{ env.MODULE }}